### ISSUE TITLE
add "label" support to markdown

### ISSUE THREAD

**Issue by niccolobusato** [thomasloven/lovelace-fold-entity-row#100]
useful to know the state of all the entities when the row is closed and many other use-cases

**Comment by thomasloven** [comment]
Huh?

**Comment by niccolobusato** [comment]
Something like this.. (ex. if the row is closed i can see if all of the light entities inside are on or off
..)
<img width="329" alt="Schermata 2020-05-16 alle 07 56 53" src="https://user-images.githubusercontent.com/44100360/82112182-dd09c300-974a-11ea-9dd0-0b260e460da7.png">

**Comment by thomasloven** [comment]
I still have no idea what you are talking about.
The label row has nothing to do with fold-entity-row, that's a feature of Home Assistant.
Markdown is an entirely different thing that's not related to this in any way, I can not add features to markdown.
The only thing in Home Assistant that supports markdown is the markdown card.
Markdown is *not* dynamic and can not show you the state of your entities.  The markdown card - however - supports *jinja2* - a different language.

Take a look at [this](https://github.com/thomasloven/lovelace-template-entity-row) perhaps?
