### ISSUE TITLE
Input_select item cropped

### ISSUE THREAD

**Issue by VDRainer** [thomasloven/lovelace-fold-entity-row#11]
Tried multiple positions, but the input_selects are alwayscropped.
![auswahl_001](https://user-images.githubusercontent.com/26381449/47286503-4406da80-d5ef-11e8-9b89-f7d12a82e1ba.png)

**Comment by jer78** [comment]
Would it be possible to have the height auto adjust so as to put other cards in the collapsed area? Would it not fix this issue as well?
