### ISSUE TITLE
open:true without collapse

### ISSUE THREAD

**Issue by sylviepipi** [thomasloven/lovelace-fold-entity-row#110]
I could use  a open:true option but without the possibility to collapse. 

![image](https://user-images.githubusercontent.com/52581925/85976643-42ec9a00-b9db-11ea-9588-b38145edb305.png)

![fold featurerequest](https://user-images.githubusercontent.com/52581925/85976575-2ea89d00-b9db-11ea-88c6-398d51b68c03.png)
![example2](https://user-images.githubusercontent.com/52581925/85977862-b7283d00-b9dd-11ea-9321-a2fc92f102b8.png)

**Comment by Sagittaq2** [comment]
Any news related with this feature?

Thanks!

**Comment by thomasloven** [comment]
If you don't want to fold the entity row, don't use fold-entity-row.
