### ISSUE TITLE
use default Header colors for dark theme

### ISSUE THREAD

**Issue by sylviepipi** [thomasloven/lovelace-fold-entity-row#111]
![example](https://user-images.githubusercontent.com/52581925/86211896-5d5b7a80-bb77-11ea-888f-57325425cced.png)

Not sure which color the header uses, but it dont seem to be able to customize it, making it very hard to read on dark themes

**Comment by thomasloven** [comment]
`section` is not a feature of fold-entity-row https://www.home-assistant.io/lovelace/entities/#section
