### ISSUE TITLE
Colors are not taken over from theme correctly

### ISSUE THREAD

**Issue by kalle2000** [thomasloven/lovelace-fold-entity-row#112]
Hi @thomasloven 

I was looking for a card like this for a long time. I am using a dark theme in lovelace and it seems the colors are not considered correctly - well, at least differently as my other cards:

![image](https://user-images.githubusercontent.com/16741825/86842513-96c74500-c0a5-11ea-9142-c04ae4057f71.png)

Is there any config I can do in my setup (i am expecting a darker color and a different formatting of the headerline)?

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Please see first line of the "Usage" section in the readme.
