### ISSUE TITLE
Card is transparent

### ISSUE THREAD

**Issue by reesericci** [thomasloven/lovelace-fold-entity-row#114]
My Home Assistant version: 228

My lovelace configuration method (GUI or yaml):

UI for almost all things, only used YAML to add  a video background.

What I am doing:

Adding the card.

What I expected to happen:

Background will look like my other cards.

What happened instead:

It is transparent.

**Minimal** steps to reproduce:

Use a video/animated background, and notice that card becomes transparent.

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by reesericci** [comment]
![image](https://user-images.githubusercontent.com/19589006/87435978-09f31e80-c5b2-11ea-80ca-806ec30d6667.png)
Here's a screenshot of what I'm talking about.

**Comment by thomasloven** [comment]
Please see first line of the "Usage" section in the README file.
> Add this to an entities card:
