### ISSUE TITLE
Feature Request: Lineup group children

### ISSUE THREAD

**Issue by niro1987** [thomasloven/lovelace-fold-entity-row#119]
Would be nice if the switches can be aligned with the parent switch.

![image](https://user-images.githubusercontent.com/7474625/89434849-59a5af80-d744-11ea-9cf3-056cb37c90a6.png)

**Comment by skynet01** [comment]
It would actually make more sense if the toggles show up in front of the arrows. That way they can align. Right now there is way to much empty space on the right side of the arrows so it looks cluttered.

![image](https://user-images.githubusercontent.com/8117544/96387278-ad297600-1155-11eb-82c7-abc4b04e817d.png)

**Comment by thomasloven** [comment]
1: The primary function of the header is to open and close the fold. Therefore the arrow should be furthest right.
2: This can't be done anyway, since the arrow is added on to a complete row over which I have no control.
