### ISSUE TITLE
Reqest to support markdown card

### ISSUE THREAD

**Issue by sasukebinbin** [thomasloven/lovelace-fold-entity-row#127]
Custom card type is supported.
But when I use type: markdown. It shows error.

Apperaciate to make it support markdown card.

**Comment by thomasloven** [comment]
Fold-entity-row works with rows, not cards.

https://github.com/thomasloven/lovelace-hui-element

**Comment by sasukebinbin** [comment]
Thanks Thomas. 
The hui element is what I’m looking for. Awesome.
