### ISSUE TITLE
Use state_color: true for non light entities 

### ISSUE THREAD

**Issue by hagak** [thomasloven/lovelace-fold-entity-row#129]
For standard entities if you set the property state_color: true it will change the entity icon for switches like it does for lights.  Be nice if this custom component could operate in the same fashion.

**Comment by thomasloven** [comment]
Please provide a minimal example.

**Comment by hagak** [comment]
type: entities
title: Living Room
state_color: true
entities:
  - switch.living_room


NOTE normally on a lovelace card if you do not set the state_color: true, only light domain entities change color based on state, however setting state_color: true you get the same behavior for other domains like switches.

**Comment by thomasloven** [comment]
Try using `group_config:`

**Comment by hagak** [comment]
group_config worked for the entities, is it possible to have that work for the head:

Example: I have a group.some_switches that is a group of switches (not a light group).  If the group is ON the state change does not happen?

**Comment by thomasloven** [comment]
```yaml
head:
  entity: group.whatever
  state_color: true```

**Comment by goliath888** [comment]
Hi @thomasloven, I was going to open an issue very similar to this one:

This is what I have:

```
  - type: 'custom:fold-entity-row'
    head: binary_sensor.all_windows
    entities:
      - binary_sensor.window_bedroom_contact
      - binary_sensor.window_kitchen_contact
```
 


A binary_sensor template with all my windows to see if there are any window opened, and then, the list of all windows.

If I put state_color: true in some entity, it works fine, but the head do not change color. I tried to put state_color in the head but did not work either. Would be possible to make state color change in the head depending if it is opened or closed?
