### ISSUE TITLE
Ability to use 'icon' in 'head'

### ISSUE THREAD

**Issue by drew-kun** [thomasloven/lovelace-fold-entity-row#151]
I would like to have an ability to specify the 'icon' in head. For example, if I do not want any group or item in the head (just use it as a section with a couple of items within) I could still use a custom MDI icon along with the label. Would be great! Thank you!

**Comment by thomasloven** [comment]
The label row is a feature of Home Assistant, not of fold-entity-row.

**Comment by drew-kun** [comment]
Thank you for your suggestion! As far as I am concerned, the template-entity-row cannot do folding (please, let me know if I am wrong). Or, do you mean, that I can somehow combine them to achieve what's described? Thanks!

**Comment by thomasloven** [comment]
> - `head:` and any row in `entities:` can be customized in exactly the same ways as ordinary entities card rows.
