### ISSUE TITLE
Request: Allow customization of head entity

### ISSUE THREAD

**Issue by fortepc** [thomasloven/lovelace-fold-entity-row#154]
![image](https://user-images.githubusercontent.com/26149601/117168414-1d1be880-ad96-11eb-87e0-b551e8f63b55.png)

![image](https://user-images.githubusercontent.com/26149601/117168212-f362c180-ad95-11eb-98ea-e49f02263128.png)
I'd like to be able to specify names and icons for the head of the fold. In the context this card is a different name makes more sense.

**Comment by thomasloven** [comment]
Try reading the readme. Like the *first row* of the "Usage" section.
