### ISSUE TITLE
Custom element doesn't exist: fold-entity-row.

### ISSUE THREAD

**Issue by grangemd** [thomasloven/lovelace-fold-entity-row#155]
when my home assistant was updated I am not getting this error inside of my ui-lovelace.yaml 

![image](https://user-images.githubusercontent.com/20445621/118399411-ffb70c00-b62a-11eb-8f05-77d6bbe9cc61.png)

**Comment by thomasloven** [comment]
Bug report template says:

> - [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Aephir** [comment]
You might want to see #168. I had a similar error, and this solved it.
