### ISSUE TITLE
the entities used are not removed from the panel

### ISSUE THREAD

**Issue by drako86** [thomasloven/lovelace-fold-entity-row#156]
My Home Assistant version: 2021.05.4

Fold-entity-row version 20.0.4:

What I am doing:

Hello everyone, first of all, sorry for my inaccurate English, but I'm not a native speaker.
my "problem" is that the entities I use are not removed from the tab of the entities used, thus creating chaos within HA
can you solve this thing?
thank you

**Comment by thomasloven** [comment]
Do you mean the Unused Entities list?
![image](https://user-images.githubusercontent.com/1299821/118727519-2ba4de00-b833-11eb-8fcc-882c0d63607e.png)


Afraid not. That's a limitation of Home Assistant.
I didn't think anyone was ever using it anyway...
