### ISSUE TITLE
tapable

### ISSUE THREAD

**Issue by NemesisRE** [thomasloven/lovelace-fold-entity-row#157]
First of all your extensions are absolutely great!

Could be just my setup, but I like to fold some cards by default and just open the fold with a click or tap.
If I enable clickable this works perfect at a PC but doesn't on mobile devices.

If this is not just an issue in my setup I would like to have something like tabable and when you set tabable secondary info should automatically move to the hold_action.

kind regards
Steven

**Comment by thomasloven** [comment]
Duplicate of the correctly filed #167
