### ISSUE TITLE
Group icons (Lights) not changing state

### ISSUE THREAD

**Issue by patrik-malina** [thomasloven/lovelace-fold-entity-row#169]
My Home Assistant version: 2021.07.3

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.4

What I am doing: creating folded group of lights

What I expected to happen: when any light turn on, state of group change to active (yellow)

What happened instead: it stays unactivated (blue icon). See pic included.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
![image](https://user-images.githubusercontent.com/73561855/126079158-c693eb53-deb2-497e-b7d8-d2146eba4648.png)

**Comment by thomasloven** [comment]
Is it a group entity or a light group?
Following the template and including your configuration would have helped.

**Comment by patrik-malina** [comment]
It is a group of entities. As follows:

group.livingroom_lights:
name: Living Room Lights
icon: mdi:lightbulb-group
entities:
    - light.living_left
    - light.living_right
    - light.living_lamp

Lovelace code:
type: entities
entities:
  - type: custom:fold-entity-row
    head: group.livingroom_lights
  - entity: light.kitchen_light
  - entity: light.bathroom_light
  - entity: light.secondbathroom
  - type: custom:fold-entity-row
    head: group.kidsroom_lights
  - entity: light.stairs_light
  - type: custom:slider-entity-row
    entity: light.bedroom
    toggle: true
    hide_when_off: true
    secondary_info: brightness
  - entity: light.entrance
state_color: true
title: Lights
icon: hass:lightbulb-group

I hope it helps.

**Comment by thomasloven** [comment]
Then everything works as expected. The group entity does not change it's icon color because the default lovelace one does not.
I recommend using a light group instead:
![image](https://user-images.githubusercontent.com/1299821/126364742-26a03dda-b611-44dd-a574-dcd47e869d1a.png)

**Comment by patrik-malina** [comment]
Thaks. I didn't know there light group exists. Need to study it 😏

**Comment by thomasloven** [comment]
https://www.home-assistant.io/integrations/light.group/
They have the same default icon as you used for your `group` entity. That's what had me confused.
