### ISSUE TITLE
Rename Entity in Head

### ISSUE THREAD

**Issue by chris1601** [thomasloven/lovelace-fold-entity-row#177]
Hi there,
first off all I have to say that I love this card. Good work. Thank you.

Now I stumbled upon a small Problem. I have the following card set up:

`type: entities
entities:
  - type: custom:fold-entity-row
    head: light.hue_haus
    open: false
    entities:
      - entity: light.hof_links
      - entity: light.hof_rechts
      - entity: light.hue_dach_einfahrt
      - entity: light.hue_dach_hof
      - entity: light.hue_dach_terrasse
      - entity: light.hue_dach_vorgarten
      - entity: light.haus_front_oben_links
      - entity: light.haus_front_oben_rechts
      - entity: light.haus_front_unten_links
      - entity: light.haus_front_unten_rechts
title: Hausbeleuchtung`

As you can see i have a general switch light.hue_haus which turns on all the entities listed below.
Is there any way to rename the switch in the header? it shows as "hue_haus" and I'd like to show it as "Hausbeleuchtung" like in the title. 
Unfortunately I cant rename the entity due to my naming scheme.

any help would be appreciated. keep up the good work.

many thanks from Germany

Chris

**Comment by thomasloven** [comment]
REAMDE:
> head: and any row in entities: can be customized in exactly the same ways as ordinary entities card rows.

**Comment by chris1601** [comment]
Sorry. Doesn't work for me. If I go like:
`type: entities
entities:
  - type: custom:fold-entity-row
    head: light.hue_haus
            label: Customizations
    entities:
      - entity: light.hof_links`
it doesn't change the name and outputs
`bad indentation of a mapping entry (5:18)

 2 | entities:
 3 |   - type: custom:fold-entity-row
 4 |     head: light.hue_haus
 5 |             label: Customizations
----------------------^
 6 |     open: false
 7 |     entities:`

**Comment by thomasloven** [comment]
That line even has a link to the relevan Home Assistant documentation.

**Comment by mplogas** [comment]
Hi @thomasloven I'm trying to wrap my head around this as well. I tried the "entity" type to have a simple toggle
```yaml
head: 
  type: entity
  label: Erdgeschoss
  entity: group.lights_eg
```
But this just yields this error
![image](https://user-images.githubusercontent.com/842121/134043239-d1997633-4765-4c9c-bb6f-2f8b9fda7c41.png)

What would be the right type here?

**Comment by thomasloven** [comment]
> head: and any row in entities: can be customized in exactly the same ways as ordinary entities card rows.

Any that works for ordinary entities card rows.

**Comment by mplogas** [comment]
makes sense now. no type definition was required according to the [docs](https://www.home-assistant.io/lovelace/entities/#options-for-entities)
