### ISSUE TITLE
Entities displayed before completely unfold

### ISSUE THREAD

**Issue by mat4444** [thomasloven/lovelace-fold-entity-row#220]
My Home Assistant version: 2022.3.3

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.12

This is a minor UI bug, but the fold-entity-row does not unfold as nicely in HA 2022.3 as in the previous releases. Basically, the hidden entities are displayed before the row is completely unfolded. Entities remained on top of all other elements until the row is completely folded again. See the video below for a more visual explanation of the problem:

https://user-images.githubusercontent.com/53400792/157545787-394eef6b-d37c-4c04-936a-b12e90bb82b0.mp4

What I expected to happen: I expected to see the same UI behavior as in 2022.2 version, where entities are not on top of each other when folding/unfolding the row.

No error from the console, same behavior in Chrome and Firefox. It must be a breaking change with HA 2022.3

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
The latest fold-entity-row version is 2.2.0. I apologize for the version number confusion.

**Comment by mat4444** [comment]
My bad, I thought it was latest version as HACS never warned me of any update. I guess it got confused when you changed the version numbering from 20 to 2.
