### ISSUE TITLE
Head with entity label changed

### ISSUE THREAD

**Issue by jvcsw** [thomasloven/lovelace-fold-entity-row#227]
** IT'S A REQUEST **

Hi everyone,

is it possible put an entity and a label in the header?
In other words, is it possible change de label of the header entity?

Thanks

Possible code:

- type: entities
    entities:
      - type: custom:fold-entity-row
        head:
          type: light.bed_light
          label: padding
        entities:
          - light.bed_light
          - light.ceiling_lights
          - light.kitchen_lights

**Comment by ildar170975** [comment]
Why not using a standard “name” property ?

**Comment by thomasloven** [comment]
From the readme:
> - `head:` and any row in `entities:` can be customized in exactly the same ways as ordinary [entities](https://www.home-assistant.io/lovelace/entities/) card rows.

**Comment by jvcsw** [comment]
Yes!!

Thank you very much.
