### ISSUE TITLE
future request: toggle group based on head

### ISSUE THREAD

**Issue by pilotak** [thomasloven/lovelace-fold-entity-row#23]
It would be nice when using `head: switch.some_switch` changes state to `on` the group will unfold and the otherway round

**Comment by thomasloven** [comment]
I believe the built-in [`conditional`](https://www.home-assistant.io/lovelace/conditional/) would be better for that.

**Comment by pilotak** [comment]
fair enough

**Comment by det-peralta** [comment]
How can we achieve this with conditional approach? @pilotak @thomasloven

**Comment by pilotak** [comment]
@det-peralta Have a look into [my setup](https://github.com/pilotak/HomeAssistant-MyConfig/blob/master/ui-lovelace.yaml#L314)
