### ISSUE TITLE
Fold entity row stopped working after latest update

### ISSUE THREAD

**Issue by msolomos** [thomasloven/lovelace-fold-entity-row#238]
![image](https://github.com/thomasloven/lovelace-fold-entity-row/assets/72358278/e78939b9-2fe0-4f90-912b-7fe72c077662)

after last update I get the following.

**Comment by ildar170975** [comment]
There is no issue observed since no code is attached.

**Comment by msolomos** [comment]
please ignore my post as it was written by mistake. problem is solved and was not related to fold entity row

**Comment by msolomos** [comment]
please ignore my post as it was written by mistake. problem is solved and was not related to fold entity row
