### ISSUE TITLE
Change name of the entity in the Head?

### ISSUE THREAD

**Issue by Jeppedy** [thomasloven/lovelace-fold-entity-row#244]
I don't see in the documentation any way to change the *name* of the entity used in the Head.
Everything works as it should, but I only see a way to give a name to the Head entry if it's a Section.

I'm glad to be wrong.

**Comment by ildar170975** [comment]
Like you do in a standard Entities card. 
Use “name” option.

**Comment by thomasloven** [comment]
See the third `NOTE:` section in the readme.

**Comment by Jeppedy** [comment]
> See the third `NOTE:` section in the readme.

Thank you for both your reply and your valuable enhancement.
Perhaps to some, the third NOTE: section speaks to this, but I've read the Entities card docs, and see nowhere that tells me how to resolve that the "name:" attribute does not change the name of the Head entity.
See my reply to Ildar for my YAML snippet.

**Comment by ildar170975** [comment]
Try
```
head:
  entity: xxx
  name: xxx
```
