### ISSUE TITLE
Horizontal stacks do not work

### ISSUE THREAD

**Issue by mirmirou** [thomasloven/lovelace-fold-entity-row#246]
My Home Assistant version: Latest 2024.3

Fold-entity-row version (FROM BROWSER CONSOLE): Latest version

What I am doing:

Trying to migrate a set of horizontal stacks into using Fold Entity Row

What I expected to happen:

Horizontal stacks are supported

What happened instead:

Horizontal stacks don't work, generate this error:

```
Unknown type encountered: horizontal-stack
```

**Comment by ildar170975** [comment]
Post a code.

**Comment by thomasloven** [comment]
horizontal-stack is not a row type

https://github.com/thomasloven/lovelace-hui-element
