### ISSUE TITLE
Indentation level and items/head

### ISSUE THREAD

**Issue by leothlon** [thomasloven/lovelace-fold-entity-row#25]
An option to set indentation of sub enteties would be nice. i manualy edited this in my js file but then i cant update it in the future.

Also would be nice if you could have both a group as head and items, i think it looks alot better with an entity as head rather than a section, but would still like to add items manualy as i want some of them to be custom cards aswell. (like the slider you made)
this is also better as you can click the header for more info dialog

optionaly specify option for certain domains on sub entities, like if "light" then use custom slider element with X settings.

**Comment by FindingJohnny** [comment]
@leothlon I was looking for the ability to change the indentation level as well. Would you mind sharing your code to make this happen? Addtionally, perhaps we could make a PR to @thomasloven 's repository to make this work if you have the code! :)

**Comment by tomlut** [comment]
Turning off indentation is an enhancement I would like to see if possible. On smaller displays the indentation can cause obscuration of entity names (particularly if using your slider-entity-row as well).

**Comment by thomasloven** [comment]
Fixed!
