### ISSUE TITLE
Remove header toggle

### ISSUE THREAD

**Issue by Kalfany** [thomasloven/lovelace-fold-entity-row#26]
Is there any way to remove/**hide** the header toggle if there is no top entity? (and without using groups)

      - type: entities
        title: Lights
        entities:
          - type: custom:fold-entity-row
            head: light.wohnzimmer
            items:
              - light.wohnzimmer_gross
              - light.wohnzimmer_klein
              - light.sofa
              - light.wohnzimmer_fenster

![zwischenablage0](https://user-images.githubusercontent.com/6972342/51495439-91e0d980-1dbc-11e9-864f-989c7ab8a9fd.jpg)

**Comment by thomasloven** [comment]
https://www.home-assistant.io/lovelace/entities/

**Comment by Kalfany** [comment]
My bad! I had it, but down at the entities part
