### ISSUE TITLE
Toggle fold with click on header label

### ISSUE THREAD

**Issue by derandiunddasbo** [thomasloven/lovelace-fold-entity-row#31]
When using header labels, it's currently necessary to tap/click on the arrow next to the label to fold/open a section. It would be nice to have an option to make the whole label (row) clickable to toggle the section.

**Comment by thomasloven** [comment]
Not currently possible. Will probably be soon, though. Leaving this open until then.

**Comment by Tosko4** [comment]
+1

**Comment by thomasloven** [comment]
Fixed!

**Comment by derandiunddasbo** [comment]
Works fine for me in Chrome W10 & Android (with 0.94.4). Thanks for your work!
