### ISSUE TITLE
Card stopped working after upgrade to 0.88.0

### ISSUE THREAD

**Issue by briis** [thomasloven/lovelace-fold-entity-row#33]
After I upgraded from 0.87.1 to 0.88.0 this Card stopped working. There is nothing in the error log, I only get the following displayed:
```
Custom element doesn't exist: fold-entity-row.
{
  "head": "group.light_outdoor_group",
  "type": "custom:fold-entity-row"
}
```
Both card-tools and this card are the latest versions

**Comment by BOZG** [comment]
> After I upgraded from 0.87.1 to 0.88.0 this Card stopped working. There is nothing in the error log, I only get the following displayed:
> 
> ```
> Custom element doesn't exist: fold-entity-row.
> {
>   "head": "group.light_outdoor_group",
>   "type": "custom:fold-entity-row"
> }
> ```
> Both card-tools and this card are the latest versions

Potentially related to this from _Noteworthy breaking changes_?

"Note for Lovelace custom card developers: if you relied on the availability of <paper-button> in your code, you will have to update it to <mwc-button> to get a similar component."

**Comment by briis** [comment]
After some more testing I found it to be a Chrome Issue. My setup works without issues on Safari.

**Comment by BOZG** [comment]
> After some more testing I found it to be a Chrome Issue. My setup works without issues on Safari.

Just checked in Firefox and getting same issue as with Chrome.

**Comment by thomasloven** [comment]
Sounds like a caching issue.
In chrome push F12 to open the dev console, then Right click the refresh button and select the bottom option to empty cache and do a full refresh.

There's probably a simmilar process in FF.

**Comment by BOZG** [comment]
> Sounds like a caching issue.
> In chrome push F12 to open the dev console, then Right click the refresh button and select the bottom option to empty cache and do a full refresh.
> 
> There's probably a simmilar process in FF.

Yep, that worked. Thought I had disabled the cache but noticed now it's only disabled when devtools is open. Thanks!

**Comment by briis** [comment]
Worked also here. Sorry for the confusion.
