### ISSUE TITLE
Not working in 0.88

### ISSUE THREAD

**Issue by resoai** [thomasloven/lovelace-fold-entity-row#34]
Unfortunately it stopped working in 0.88.  I can see following error in the console:

```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Function.litElement (card-tools.js:15)
    at customElements.whenDefined.then (fold-entity-row.js:2)
```

**Comment by Neburb** [comment]
Same error for me. Tried also updating card-tools to the latest version, and gives another error:

```
ReferenceError: cardTools is not defined
    at customElements.whenDefined.then (fold-entity-row.js)
```

**Comment by thomasloven** [comment]
#33

**Comment by resoai** [comment]
Not a caching issue, I'm afraid.

**Comment by Neburb** [comment]
@thomasloven I don't know if this helps, but the last commit you made to the card-tools repo worked, but gives another error:
```
Uncaught TypeError: Cannot read property 'shadowRoot' of null
    at Object.cardTools.fireEvent (card-tools.js:40)
    at card-tools.js:180
```

at this line:

https://github.com/thomasloven/lovelace-card-tools/blob/deb8e38741b7472cd92c50f69fb417e49ad2cb1d/card-tools.js#L41

**Comment by Neburb** [comment]
Welp.. That was my fault, I didn't updated card-tools to the latest version.

I also had to add this line:
```
var cardTools = customElements.get('card-tools');
```
to the start of the fold-entity-row.js file, just inside the `customElements.whenDefined` part, because it was giving me the error that I mentioned in another comment.

**Comment by thomasloven** [comment]
That's because you use `type: module` instead of `type: js`. I should make that more clear in the documentation.

**Comment by Neburb** [comment]
>That's because you use `type: module` instead of `type: js`. I should make that more clear in the documentation.

Yep, you are right, sorry about that, didn't notice it in the readme.
You know, I think it is my fault, is pretty clear in the guide, if you mean [this one](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins), but I've been using this since lovelace implementation. I think it didn't had the "type" attribute from the start? Anyway, I think I just copy and paste "type: module" in all the resources, and it just worked, so I didn't worried about it.

**Comment by resoai** [comment]
I'm sorry guys, but I still have the same error in the console:

````
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Function.litElement (card-tools.js:15)
    at customElements.whenDefined.then (fold-entity-row.js:2)
````

UI shows "Custom element doesn't exist: fold-entity-row."

**Comment by thomasloven** [comment]
No. Type has always been there, and the guide is really not clear at all. Besides, I should adapt my cards to work with either method.

But anyway, @resoai; please make sure you really have the latest version of card-tools. The custom_updater's been known to fail before. Line 15 *should* read ` return Object.getPrototypeOf(customElements.get('home-assistant-main'));`

**Comment by resoai** [comment]
@thomasloven ouch! card-tools was indeed the issue! Thanks so much!
