### ISSUE TITLE
after updating to 0.88.0 i'm getting this error

### ISSUE THREAD

**Issue by t0mer** [thomasloven/lovelace-fold-entity-row#35]
![image](https://user-images.githubusercontent.com/4478920/53206454-ad4c3800-3639-11e9-9ab2-469c429efdcd.png)

**Comment by sagatxxx** [comment]
Same here!
Some cards have also failed and I have had to update them to versions released in the last hours, please could update this one too, it is very helpful, thank you very much

**Comment by thomasloven** [comment]
Make sure you have the latest version of card-tools.

**Comment by Aephir** [comment]
I have card-tools version 0.3 (deb8e3 in the custom updater card), but still see the same as shown above (after clearing cache) in Chrome.
