### ISSUE TITLE
option: show arrow left of the toggle

### ISSUE THREAD

**Issue by capstan1** [thomasloven/lovelace-fold-entity-row#37]
I have a card mixed of "normal" entities and fold-entities.
When doing this, the toggles are out of place because of the folding arrow.
![image](https://user-images.githubusercontent.com/17147867/54072425-e7911880-427a-11e9-8352-6071cd91603b.png)

Can there be a option to put the arrow left of the toggle so all toggles are in line?

**Comment by thomasloven** [comment]
That's not easily done, since the entire row - including the toggle - is a core lovelace element.

Besides, the major function should be the rightmost, and for a folding row, that's to unfold.
