### ISSUE TITLE
possibility to get rid of row toggle

### ISSUE THREAD

**Issue by GatoPharaoh** [thomasloven/lovelace-fold-entity-row#38]
Hi!
Is there some way to get rid of the toggles in the row? I tried it with `control:hidden` and `show_header_toggle: false` but both didn't work. Is it even possible?

thanks in advance

![grafik](https://user-images.githubusercontent.com/12106737/54480497-6a8d1280-4829-11e9-869a-b54b39faf77c.png)

**Comment by thomasloven** [comment]
I'll look into making a new plugin for a row type with only icon and name.

#40

**Comment by thomasloven** [comment]
Try using this as header: https://github.com/thomasloven/lovelace-dummy-entity-row

**Comment by jazzyisj** [comment]
Does what I need and then some.  Thank you good sir!

**Comment by GatoPharaoh** [comment]
works! thank you very much!
