### ISSUE TITLE
Override friendly_name on the head entity

### ISSUE THREAD

**Issue by dimmanramone** [thomasloven/lovelace-fold-entity-row#41]
This is not really a issue, but a feature request. 

I'm trying to rename the entity of the head but it seems that either I'm doing something wrong or it is not possible to do that.

**Comment by thomasloven** [comment]
All options that work for normal entity card rows work with the header row.

**Comment by dimmanramone** [comment]
Ok I tried that, so I obviously doing something wrong. Can you give an example how to rename an entity that's on the head?

**Comment by thomasloven** [comment]
```
head:
  entity: light.bed_light
  name: Renamed entity
```

For future reference, please follow the bullet list here regarding support requests: https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#things-suddenly-stopped-working

**Comment by dimmanramone** [comment]
Thanks for the help. That did the trick. I actually was expecting that is should be like the following example
```
head:
  - entity: light.bed_light
    name: Renamed entity
```
