### ISSUE TITLE
How to change entity ${this._head} from using --primary-color

### ISSUE THREAD

**Issue by Tosko4** [thomasloven/lovelace-fold-entity-row#47]
in the javascript fold-entity-row.js on row 16 it prints the entity name **${this._head}**

But the font color used in this div is grabbing the --primary-color 
I would like to overwrite that ${this._head} is not in the color that --primary-color is, but would like to give that a different color. Like white for example. I tried to style the div with entry as id, i tried to wrap font html tags around it with a color, but no succes.

Please help me in the right direction.

<img width="678" alt="Screenshot 2019-05-02 at 15 13 56" src="https://user-images.githubusercontent.com/1294707/57077704-fe893f80-6cec-11e9-8b2d-ad2370479489.png">

**Comment by thomasloven** [comment]
You could wrap the row in card-modder and set `--primary-color` to whatever you want.

Practice it without fold-entity-row first.

**Comment by thomasloven** [comment]
Or if you'd rather edit the .js file, you can add `--primary-color: white;` in here: https://github.com/thomasloven/lovelace-fold-entity-row/blob/master/fold-entity-row.js#L42-L45
