### ISSUE TITLE
Cursor doesn't change on hovering

### ISSUE THREAD

**Issue by definitio** [thomasloven/lovelace-fold-entity-row#48]
Mouse cursor doesn't change to pointer when hovering.

**Comment by thomasloven** [comment]
Change to what when hovering what?

**Comment by definitio** [comment]
Look at mouse cursor.
This is fold-entity-row:
![fold-entity-row](https://user-images.githubusercontent.com/37266727/59494410-20561480-8e9e-11e9-906f-5afac02b6c90.png)
Everything else:
![everything_else](https://user-images.githubusercontent.com/37266727/59494484-4bd8ff00-8e9e-11e9-9196-1e45a2f264ac.png)

**Comment by thomasloven** [comment]
Fixed!

**Comment by definitio** [comment]
Thank you! It mostly works, but arrow still has old behaviour. Can it be fixed too?
![Screenshot_20190623_223930](https://user-images.githubusercontent.com/37266727/59980502-f15f4180-9607-11e9-91a2-651b95ab2340.png)

**Comment by thomasloven** [comment]
I experimented a bit with different pointe styles in the latest head release... Not sure what I think about it...
1e92389fae1cbdd2a3ce7be2d696c53e3d854f48
