### ISSUE TITLE
Overflow: hidden or overflow:none causes slider input tooltip to be hidden

### ISSUE THREAD

**Issue by andrewdolphin** [thomasloven/lovelace-fold-entity-row#53]
My Home Assistant version: Latest

My lovelace configuration method (GUI or yaml): YAML

What I am doing:

Using fold-entity-row my top item is a slider input (actually a slider-entity-row)

What happened instead:

The tooltip to show the currently dragged/selected number gets hidden behind the header row.

Error messages from the browser console:

None
---

Changing:
```
 #items[open] {
        overflow: none;
        max-height: none;
```
to
```
 #items[open] {
        overflow: visible;
        max-height: none;
```
in the plugin resolves the issue

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x ] Have made sure I am using the latest version of the plugin.

[x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Thank you!
