### ISSUE TITLE
Fold cards not just entity

### ISSUE THREAD

**Issue by amulyawan** [thomasloven/lovelace-fold-entity-row#56]
hi,
It only works for entity, any advise to fold "cards:"
If click toggle on and show below cards of entity buttons of remote.

![image](https://user-images.githubusercontent.com/41641732/61091219-81f0ab00-a46b-11e9-8894-86aa14da41f2.png)

**Comment by thomasloven** [comment]
This might help you: https://github.com/thomasloven/hass-config/wiki/Misc-tricks#cardelemententity-row-triality

**Comment by amulyawan** [comment]
Hi,

Thanks for the tips.
![image](https://user-images.githubusercontent.com/41641732/61178750-e2274e80-a61d-11e9-8fd8-b463ca94c3f9.png)
![image](https://user-images.githubusercontent.com/41641732/61178754-f10e0100-a61d-11e9-9b3f-c1e6af7f70d8.png)
![image](https://user-images.githubusercontent.com/41641732/61178757-fa976900-a61d-11e9-8ff8-90414cc4b08e.png)

ui-lovelace.yaml
`views:
  - title: Main
    icon: 'mdi:home'
    cards:
      - type: markdown
        content: |
          ## Air Conditioner
      - type: vertical-stack
        cards:
          - entities:
              - entity: climate.ac_ruang_tamu
            type: entities
          - entities:
              - entity: climate.ac_kamar_utama
            type: entities
          - entities:
              - entity: climate.ac_kamar_kecil
            type: entities
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Ruang Tamu - Media
          - type: custom:hui-divider-row
#HDMI Switch
          - type: vertical-stack
            cards:
              - type: custom:fold-entity-row
                head:
                  type: custom:hui-markdown-card
                  content: |
                    ### HDMI Switch
                style: |
                  ha-markdown.markdown.no-header {
                    padding-top: 2px;
                  }
                padding: 5
                entities:
                  !include /config/lovelace/hdmi_switch.yaml
          - type: custom:hui-divider-row
#STB Indihome
          - type: vertical-stack
            cards:
              - type: custom:hui-markdown-card
                style: |
                  ha-markdown.markdown.no-header {
                    height: 20px;
                  }
                content: |
                  ### STB Indihome
              - type: custom:hui-horizontal-stack-card
                cards:
                  - type: custom:hui-entity-button-card
                    entity: switch.stbindihome_power
                    name: Power
                    icon: 'mdi:power'
                    show_name: false
                    tap_action:
                      action: toggle
                    style: |
                      ha-card {
                        height: 30px;
                      }
                      ha-icon {
                        height: 21px;
                      }
                  - type: custom:hui-entity-button-card
                    entity: switch.stbindihome_volumemute
                    name: Volume mute
                    icon: 'mdi:volume-off'
                    show_name: false
                    tap_action:
                      action: toggle
                    style: |
                      ha-card {
                        height: 30px;
                      }
                      ha-icon {
                        height: 21px;
                      }
              - type: custom:hui-horizontal-stack-card
                style: |
                  hui-horizontal-stack-card {
                  height: 10px;
                  }
                cards:
                  - type: custom:fold-entity-row
                    head:
                      type: custom:hui-section-row
                      label: Remote
                    padding: 5
                    entities:
                      !include /config/lovelace/stb_indihome.yaml
          - type: custom:hui-divider-row

`
stb_indihome.yaml
`  - type: custom:hui-divider-row
    style:
      height: 10px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_menu
        name: Menu
        show_icon: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
            color: [[ if(switch.stbindihome_menu == "on", #FEB221, #4481eb) ]];
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_navigationup
        name: Navigation Up
        icon: 'mdi:arrow-up'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_app
        name: App
        show_icon: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
            color: [[ if(switch.stbindihome_app == "on", #FEB221, #4481eb) ]];
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_navigationleft
        name: Navigation Left
        icon: 'mdi:arrow-left'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_buttonok
        name: OK
        show_icon: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
            color: [[ if(switch.stbindihome_buttonok == "on", #FEB221, #4481eb) ]];
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_navigationright
        name: Navigation Right
        icon: 'mdi:arrow-right'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_back
        name: Back
        show_icon: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
            color: [[ if(switch.stbindihome_back == "on", #FEB221, #4481eb) ]];
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_navigationdown
        name: Navigation Down
        icon: 'mdi:arrow-down'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel_info
        name: Info
        show_icon: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
            color: [[ if(switch.stbindihome_channel_info == "on", #FEB221, #4481eb) ]];
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_rewind
        name: Rewind
        icon: 'mdi:rewind'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_forward
        name: Rewind
        icon: 'mdi:fast-forward'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_playpause
        name: Play / Pause
        icon: 'mdi:play-pause'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_stop
        name: Stop
        icon: 'mdi:stop'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_volumeup
        name: Volume Up
        icon: 'mdi:volume-plus'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_previous
        name: Skip Previous
        icon: 'mdi:skip-previous'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channelnext
        name: Channel Next
        icon: 'mdi:plus'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_volumedown
        name: Volume Down
        icon: 'mdi:volume-minus'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_previous
        name: Skip Next
        icon: 'mdi:skip-forward'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channelprevious
        name: Channel Next
        icon: 'mdi:minus'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel1
        name: 1
        icon: 'mdi:numeric-1'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel2
        name: 2
        icon: 'mdi:numeric-2'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel3
        name: 3
        icon: 'mdi:numeric-3'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel4
        name: 4
        icon: 'mdi:numeric-4'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel5
        name: 5
        icon: 'mdi:numeric-5'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel6
        name: 6
        icon: 'mdi:numeric-6'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel7
        name: 7
        icon: 'mdi:numeric-7'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel8
        name: 8
        icon: 'mdi:numeric-8'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel9
        name: 9
        icon: 'mdi:numeric-9'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_pip
        name: PIP
        show_icon: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
            color: [[ if(switch.stbindihome_pip == "on", #FEB221, #4481eb) ]];
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_channel0
        name: 0
        icon: 'mdi:numeric-0'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.stbindihome_lastchannel
        name: Last Channel
        icon: 'mdi:repeat'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 28px;
          }`
hdmi_switch.yaml
`  - type: custom:hui-divider-row
    style:
      height: 10px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.hdmi_switcher_1
        name: 1
        icon: 'mdi:numeric-1'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 30px;
          }
          ha-icon {
            height: 21px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.hdmi_switcher_2
        name: 2
        icon: 'mdi:numeric-2'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 30px;
          }
          ha-icon {
            height: 21px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.hdmi_switcher_3
        name: 3
        icon: 'mdi:numeric-3'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 30px;
          }
          ha-icon {
            height: 21px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.hdmi_switcher_4
        name: 4
        icon: 'mdi:numeric-4'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 30px;
          }
          ha-icon {
            height: 21px;
          }
  - type: custom:hui-divider-row
    style:
      height: 5px
  - type: custom:hui-horizontal-stack-card
    cards:
      - type: custom:hui-entity-button-card
        entity: switch.hdmi_switcher_down
        name: Down
        icon: 'mdi:arrow-down-bold'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 30px;
          }
          ha-icon {
            height: 21px;
          }
      - type: custom:hui-entity-button-card
        entity: switch.hdmi_switcher_ok
        name: OK
        show_icon: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 30px;
            color: [[ if(switch.hdmi_switcher_ok == "on", #FEB221, #4481eb) ]];
          }
      - type: custom:hui-entity-button-card
        entity: switch.hdmi_switcher_up
        name: Up
        icon: 'mdi:arrow-up-bold'
        show_name: false
        tap_action:
          action: toggle
        style: |
          ha-card {
            height: 30px;
          }
          ha-icon {
            height: 21px;
          }
`
