### ISSUE TITLE
Bring cards into the fold

### ISSUE THREAD

**Issue by boozelclark** [thomasloven/lovelace-fold-entity-row#71]
With lovelace-card-tools it's possible to use card-maker to generate cards. It would be great if lovelace-fold-entity-row could have other cards added as rows. I'm struggling to build it from the source for a pull request but if anyone else is able it would be great.

**Comment by thomasloven** [comment]
https://github.com/thomasloven/hass-config/wiki/Misc-tricks#cardelemententity-row-triality

I'd forgotten to push my changes to the build-chain, btw.
Now to build from source, you just need to install node and run `npm install` and `npm run build`
