### ISSUE TITLE
allow templating in head fields

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#78]
as per https://community.home-assistant.io/t/fold-entity-row-hide-away-stuff-in-entities-cards/140454/25?u=mariusthvdb

please allow templating the head field:

```
      - type: custom:fold-entity-row
        head:
          type: section
          label: >
            {% set unknown = states|selectattr('state','eq','unknown')|map(attribute='entity_id')|list %}
            Unknown entities: ({{ unknown|count }})
```

now you've created template-entity-row, I was kind of hoping this would also be an option for fold-entity-row?
thanks for considering.

**Comment by SdeGeata** [comment]
I second this request! I would love to template the "open" state according to the state of another entity. Thanks and keep up the great work!

**Comment by jazzyisj** [comment]
This would definitely be one on my wish list.  Tried using the card templater plugin but open wants a boolean and templates output strings.  The ability to do the following would be just peachy!

```
  - type: custom:fold-entity-row
    head: binary_sensor.system_update
    open: "{{ true is_state('binary_sensor.system_update','on') else false }}"
```

**Comment by thomasloven** [comment]
Just use template-entity-row in the head then.

**Comment by danodemano** [comment]
@thomasloven - can you elaborate please?

**Comment by thomasloven** [comment]
[This](https://github.com/thomasloven/lovelace-template-entity-row). The best way to get the head to behave like a template-entity-row is to make head a template-entity-row.
