### ISSUE TITLE
Ability to collapse row after selection

### ISSUE THREAD

**Issue by jeremywillans** [thomasloven/lovelace-fold-entity-row#79]
Is there a possibility of adding a method of collapsing the group after a selection is made within the Fold Entity Row?

Example:
[I am using](https://community.home-assistant.io/t/irobot-roomba-i7-configuration-using-rest980/161175?u=syrius) a selection of Input Booleans for Vacuum Cleaning room selection and a "Clean" button, ideally it would be awesome if the group could collapse after clicking this!
  

Thanks for your consideration!

**Comment by thomasloven** [comment]
That would require fold-entity-row to know what "selection" *means* for *every* kind of thing that can be put in an entities card. Including custom stuff.

That's just not a reasonable endeavour.
