### ISSUE TITLE
Update documentation: group.all_* no longer supported

### ISSUE THREAD

**Issue by rschuiling** [thomasloven/lovelace-fold-entity-row#84]
As of Home Assistant v0.104.0, the groups containing all entities (e.g. group.all_automations, group.all_lights etc) are no longer available (see [Breaking changes](https://www.home-assistant.io/blog/2020/01/15/release-104/#breaking-changes)).

Perhaps it would be nice to remove references to group.all_ from the documentation?

**Comment by thomasloven** [comment]
You can still create a group called `all_lights` manually. The example is as good as any other.
