### ISSUE TITLE
Section not working in 0.106.0b2

### ISSUE THREAD

**Issue by jmutnick** [thomasloven/lovelace-fold-entity-row#87]
My Home Assistant version: 0.106.0b2

My lovelace configuration method (GUI or yaml): yaml

What I am doing:

          - type: custom:fold-entity-row
            head:
              type: section
              label: Flu Data

What I expected to happen:
 expecting it to work per documentation and how it did in 0.105.5

What happened instead:

Custom element doesn't exist: hui-section-row.
type: section
label: Flu Data

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [xx ] Have made sure I am using the latest version of the plugin.
- [ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
I note that you haven't checked the mark indicating that you have followed the troubleshooting steps...

The first step of that guide tells you to make sure you are using [the latest version](https://github.com/thomasloven/lovelace-fold-entity-row/releases/tag/14), which was released five days ago to fix exactly this problem.

**Comment by manonstreet** [comment]
@thomasloven:  I'm not sure about @jmutnic, but I am using version 14 and still face this issue.

**Comment by jmutnick** [comment]
Yes, I am also on 14.  I just forgot to check that box.

**Comment by thomasloven** [comment]
I just installed version 14 on the latest dev branch, and it works there with 
```yaml
type: entities
entities:
  - type: 'custom:fold-entity-row'
    head:
      type: section
    entities:
      - light.bed_light
```

Please check your caches and/or try reinstalling.

**Comment by manonstreet** [comment]
Thanks Thomas.  Are there any other troubleshooting steps to try?  I've cleared my cache and reinstalled the component, but I cannot get your example to render:

![image](https://user-images.githubusercontent.com/2609655/75161382-b3ac3e80-56e9-11ea-8b92-89fbd1d6c235.png)

To note, I am running .106b1.  Beta two is not show in my UI for upgrade for some strange reason even though I am subscribed to the beta channel.  I see here:
https://github.com/home-assistant/home-assistant/releases

that there is a frontend upgrade.  Perhaps that's issue...

**Comment by manonstreet** [comment]
I upgraded to beta 4, and also uninstalled this custom component and reinstalled it.  Back in business.
