### ISSUE TITLE
Support state_color

### ISSUE THREAD

**Issue by tomlut** [thomasloven/lovelace-fold-entity-row#92]
Could you please add support for   `state_color:` ?

Currently I have enormous folded lists that I have to add  `state_color:`  to each individual entity to get it to use state colour.

**Comment by thomasloven** [comment]
Anything that's supported by an entities row is supported by fold-entity-row.

Options can be added to all entities using `group_config`.

**Comment by tomlut** [comment]
> group_config. 

Oh! Of course. 

Apologies for wasting your time.
